### ISSUE TITLE
renderer to renderer

### ISSUE THREAD

**Issue by greg9504** [vivimice/electron-ipcfy#1]
Hello,

I'm trying to use the library but I'm not able to get it to work.  I have a fairly simple use case.  I have two renderer windows.  The second is opened by the first using new BrowserWindow.  In the second I want to send a message to the first after some work completes.  In the first I then react to the message.  However I'm not receiving the message in the first one.

Here is my simple service:

```
import { ipcfy } from 'electron-ipcfy';

export interface MosaicToPdfServiceInterface {
    readyToPrint(winid: number): void;
}

export const mosaicPdfService = ipcfy<MosaicToPdfServiceInterface>('mosaictopdf');

```

In the first renderer I attach an implementation: 

```
mosaicPdfService.__attachImpl(new class implements MosaicToPdfServiceInterface {
                public readyToPrint(winid: number): void {
                    debugger;
                    console.log('got message from print window ' + winid);
                }
            });

```

Then in the second renderer I call the service:

`mosaicPdfService.readyToPrint(remote.getCurrentWindow().id);`

However I never get the message in the first renderer. 

Debugging the call to readyToPrint, I get to equivalent of line 270 of IpcRegistry.ts, then in the call to probeRemoteHandlerLocation I get to line 298 (ipcRenderer.send(queryChannel, topic);) after that I'm not able to follow the debugging well.

Is there something I'm missing?  It's an Angular app (7.2.14) but I don't think that should matter.

Thanks.

**Comment by vivimice** [comment]
Have you tried move implementation to main process ?

If that would solve the problem, it may indicates that implemetation is not registered in 2nd renderer upon call in 1st render

**Comment by vivimice** [comment]
There is a demo in https://github.com/vivimice/electron-ipcfy/tree/master/packages/electron-ipcfy-demo shows inter-renderer ipc calls which is similar to your code

Hope it will help you out

**Comment by greg9504** [comment]
Hello,
I haven't tried to move the implementation to the main thread.  I'll give it a try to see if that changes anything, however ideally I would like to have it work renderer to renderer.

Thanks for the reply.

**Comment by vivimice** [comment]
Close this issue due to inactivity
